<?php

return [

    "scripts" => [
            "recove" => [
                "CREATE TABLE IF NOT EXISTS bitacora_cove (
                    id int(11) NOT NULL AUTO_INCREMENT,
                    bitacora_pedimento_id int(11) NOT NULL,
                    cove varchar(20) NOT NULL,
                    observaciones text,
                    status int(11) DEFAULT '0',
                    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id)
                )",

                "CREATE TABLE IF NOT EXISTS bitacora_recove (
                    id int(11) NOT NULL AUTO_INCREMENT,
                    aduana varchar(3) DEFAULT '0',
                    patente varchar(4) DEFAULT '0',
                    pedimento varchar(7) DEFAULT '0',
                    operacion varchar(30) DEFAULT NULL,
                    fecha date DEFAULT '0000-00-00',
                    partidas text,
                    tpartidas int(11) DEFAULT NULL,
                    status int(11) DEFAULT '0',
                    bitacora int(11) DEFAULT '0',
                    observaciones text,
                    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (id)
                )",

                "CREATE TABLE IF NOT EXISTS caem01 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_emp varchar(6) NOT NULL,
                    emp_nomemp varchar(60) DEFAULT NULL,
                    emp_razonsoc varchar(200) DEFAULT NULL,
                    emp_rfcemp varchar(13) DEFAULT NULL,
                    emp_calemp varchar(80) DEFAULT NULL,
                    emp_colemp varchar(30) DEFAULT NULL,
                    emp_nueemp varchar(6) DEFAULT NULL,
                    emp_nuiemp varchar(6) DEFAULT NULL,
                    emp_mpoemp varchar(60) DEFAULT NULL,
                    emp_edoemp varchar(60) DEFAULT NULL,
                    emp_codemp varchar(5) DEFAULT NULL,
                    emp_pais varchar(120) DEFAULT NULL,
                    emp_lademp char(3) DEFAULT NULL,
                    emp_telemp varchar(12) DEFAULT NULL,
                    emp_faxemp varchar(12) DEFAULT NULL,
                    emp_repemp varchar(80) DEFAULT NULL,
                    emp_rfremp varchar(13) DEFAULT NULL,
                    emp_curpemp varchar(18) DEFAULT NULL,
                    emp_domicilioe varchar(60) DEFAULT NULL,
                    emp_telefonoe varchar(12) DEFAULT NULL,
                    emp_autorizae varchar(15) DEFAULT NULL,
                    emp_podere varchar(20) DEFAULT NULL,
                    emp_diremp varchar(50) DEFAULT NULL,
                    emp_cveemp varchar(8) DEFAULT NULL,
                    emp_alr varchar(4) DEFAULT NULL,
                    emp_entfed char(2) DEFAULT NULL,
                    emp_locemp varchar(30) DEFAULT NULL,
                    emp_logoemp blob,
                    emp_logomime varchar(40) DEFAULT NULL,
                    emp_licencia mediumtext,
                    emp_callplanta varchar(60) DEFAULT NULL,
                    emp_mpoplanta varchar(60) DEFAULT NULL,
                    emp_cpplanta varchar(5) DEFAULT NULL,
                    emp_colplanta varchar(40) DEFAULT NULL,
                    emp_efplanta varchar(60) DEFAULT NULL,
                    emp_telplanta varchar(12) DEFAULT NULL,
                    emp_faxplanta varchar(12) DEFAULT NULL,
                    emp_neplanta varchar(10) DEFAULT NULL,
                    emp_niplanta varchar(10) DEFAULT NULL,
                    emp_actividad varchar(100) DEFAULT NULL,
                    emp_bom int(11) DEFAULT NULL,
                    emp_gpo int(11) DEFAULT NULL,
                    emp_certificada tinyint(4) DEFAULT '0',
                    emp_autopartes tinyint(4) DEFAULT '0',
                    emp_explosiona tinyint(4) DEFAULT '0',
                    emp_remanufactura tinyint(4) DEFAULT '0',
                    emp_fechacce date DEFAULT NULL,
                    emp_ftpdir varchar(120) DEFAULT NULL,
                    emp_ftpusr varchar(20) DEFAULT NULL,
                    emp_ftppswd varchar(20) DEFAULT NULL,
                    emp_ftppto smallint(6) DEFAULT NULL,
                    emp_ftpmail text,
                    emp_scccg date DEFAULT NULL,
                    UNIQUE KEY pk_emp (pk_emp),
                    UNIQUE KEY pk_item (pk_item)
                )",

                "CREATE TABLE IF NOT EXISTS caem06 (
                    pk_age varchar(4) NOT NULL,
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_emp varchar(6) DEFAULT NULL,
                    age_razon varchar(200) DEFAULT NULL,
                    age_curp varchar(18) DEFAULT NULL,
                    age_rfc varchar(13) DEFAULT NULL,
                    age_calle varchar(100) DEFAULT NULL,
                    age_col varchar(60) DEFAULT NULL,
                    age_cp varchar(10) DEFAULT NULL,
                    age_mpo varchar(60) DEFAULT NULL,
                    age_edo varchar(60) DEFAULT NULL,
                    age_pais varchar(60) DEFAULT NULL,
                    age_tel varchar(10) DEFAULT NULL,
                    age_fax varchar(10) DEFAULT NULL,
                    age_cont varchar(100) DEFAULT NULL,
                    age_mail varchar(100) DEFAULT NULL,
                    age_repleg varchar(60) DEFAULT NULL,
                    age_rfcrep varchar(13) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    UNIQUE KEY pk_age (pk_age,pk_emp)
                )",

                "CREATE TABLE IF NOT EXISTS caem16 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_emp varchar(6) NOT NULL,
                    sello_rfc char(13) DEFAULT NULL,
                    sello_key varchar(255) DEFAULT NULL,
                    sello_cer varchar(255) DEFAULT NULL,
                    sello_vigencia date DEFAULT NULL,
                    sello_ultimafirma date DEFAULT NULL,
                    sello_password varchar(255) DEFAULT NULL,
                    sello_wsp varchar(255) DEFAULT NULL,
                    sello_key64 text,
                    sello_cer64 text,
                    sello_observa mediumtext,
                    sello_tipofigura int(4) DEFAULT '5',
                    PRIMARY KEY (pk_item)
                )",

                "CREATE TABLE IF NOT EXISTS cove_comprobante (
                    inv_item int(11) NOT NULL AUTO_INCREMENT,
                    inv_cove varchar(40) DEFAULT NULL,
                    pk_item int(11) DEFAULT NULL,
                    inv_factura varchar(40) NOT NULL,
                    inv_fecha date NOT NULL DEFAULT '0000-00-00',
                    inv_moneda varchar(10) DEFAULT 'USD-USA',
                    inv_factorme decimal(12,6) DEFAULT '1.000000',
                    inv_subdivision smallint(4) DEFAULT NULL,
                    inv_certorigen smallint(6) DEFAULT NULL,
                    inv_noexpconfiable varchar(50) DEFAULT NULL,
                    emisor_tipoid smallint(6) NOT NULL,
                    emisor_clave varchar(20) DEFAULT ' ',
                    emisor_identificador varchar(50) DEFAULT NULL,
                    emisor_paterno varchar(200) DEFAULT ' ',
                    emisor_materno varchar(200) DEFAULT NULL,
                    emisor_nombre varchar(200) DEFAULT NULL,
                    emisor_calle varchar(100) DEFAULT NULL,
                    emisor_noext varchar(55) DEFAULT NULL,
                    emisor_noint varchar(55) DEFAULT NULL,
                    emisor_col varchar(120) DEFAULT NULL,
                    emisor_localidad varchar(120) DEFAULT 'S',
                    emisor_mpo varchar(120) DEFAULT NULL,
                    emisor_edo varchar(120) DEFAULT NULL,
                    emisor_pais varchar(120) DEFAULT NULL,
                    emisor_cp varchar(12) DEFAULT NULL,
                    dest_tipoid smallint(6) DEFAULT NULL,
                    dest_clave varchar(20) DEFAULT NULL,
                    dest_identificador varchar(50) DEFAULT NULL,
                    dest_paterno varchar(200) DEFAULT NULL,
                    dest_materno varchar(200) DEFAULT NULL,
                    dest_nombre varchar(200) DEFAULT NULL,
                    dest_calle varchar(100) DEFAULT NULL,
                    dest_noext varchar(55) DEFAULT NULL,
                    dest_noint varchar(55) DEFAULT NULL,
                    dest_col varchar(120) DEFAULT NULL,
                    dest_localidad varchar(120) DEFAULT NULL,
                    dest_mpo varchar(120) DEFAULT NULL,
                    dest_edo varchar(30) DEFAULT NULL,
                    dest_pais varchar(120) DEFAULT NULL,
                    dest_cp varchar(12) DEFAULT NULL,
                    transCode varchar(9) DEFAULT NULL,
                    transName varchar(50) DEFAULT NULL,
                    transRFC varchar(25) DEFAULT NULL,
                    transAddr1 varchar(50) DEFAULT NULL,
                    transAddr2 varchar(50) DEFAULT NULL,
                    transAddr3 varchar(50) DEFAULT NULL,
                    transCntryOfOrigin varchar(3) DEFAULT NULL,
                    transSCAC varchar(4) DEFAULT NULL,
                    transCAAT varchar(5) DEFAULT NULL,
                    transTrailer varchar(25) DEFAULT NULL,
                    transBox varchar(25) DEFAULT NULL,
                    transPlacaTrailer varchar(20) DEFAULT NULL,
                    transPlacaBox varchar(20) DEFAULT NULL,
                    transChofer varchar(40) DEFAULT NULL,
                    transSello varchar(40) DEFAULT NULL,
                    shipto_clave varchar(20) DEFAULT NULL,
                    shipto_name varchar(60) DEFAULT NULL,
                    shipto_addr1 varchar(60) DEFAULT NULL,
                    shipto_addr2 varchar(60) DEFAULT NULL,
                    shipto_addr3 varchar(60) DEFAULT NULL,
                    shipto_addr4 varchar(60) DEFAULT NULL,
                    filer_clave varchar(20) DEFAULT NULL,
                    inv_tipocambio decimal(11,5) DEFAULT NULL,
                    transTipo int(11) DEFAULT NULL,
                    PRIMARY KEY (inv_item),
                    KEY pk_factura (inv_factura)
                )",

                "CREATE TABLE IF NOT EXISTS cove_detalle (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    inv_cove varchar(25) DEFAULT NULL,
                    inv_item int(11) DEFAULT NULL,
                    inv_marca varchar(100) DEFAULT NULL,
                    inv_modelo varchar(50) DEFAULT NULL,
                    inv_submodelo varchar(50) DEFAULT NULL,
                    inv_noserie varchar(25) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY inv_cove (inv_cove,inv_item)
                )",

                "CREATE TABLE IF NOT EXISTS cove_encabezado (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_tipo int(4) DEFAULT '1',
                    pk_referencia varchar(40) DEFAULT NULL,
                    cove_remesa int(11) DEFAULT '0',
                    cove_patente varchar(4) DEFAULT NULL,
                    cove_factura varchar(40) NOT NULL,
                    cove_relacion smallint(4) DEFAULT '0',
                    cove_subdivision smallint(4) DEFAULT '0',
                    cove_fecha date DEFAULT NULL,
                    cove_certorigen smallint(6) DEFAULT '0',
                    cove_noexpconfiable varchar(50) DEFAULT NULL,
                    cove_observa text,
                    cove_rfcconsulta varchar(13) DEFAULT NULL,
                    cove_edocument varchar(20) DEFAULT NULL,
                    cove_fecha_edocument date DEFAULT NULL,
                    cove_operacion varchar(20) DEFAULT NULL,
                    cove_status varchar(20) DEFAULT 'SIN COVE',
                    cove_captura varchar(20) DEFAULT NULL,
                    cove_fechacap timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    cove_adenda int(11) DEFAULT '0',
                    cove_numadenda varchar(20) DEFAULT '',
                    cove_firma varchar(250) DEFAULT NULL,
                    cove_fechafirma datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
                    cove_cadenaoriginal text,
                    cove_sellosolicita text,
                    cove_sellovucem text,
                    cove_xml text,
                    entry_numero char(10) DEFAULT NULL,
                    entry_broker char(4) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY pk_factura (pk_tipo,cove_factura)
                )",

                "CREATE TABLE IF NOT EXISTS cove_mercancia (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    inv_cove varchar(40) DEFAULT NULL,
                    inv_factura varchar(40) DEFAULT NULL,
                    inv_item int(11) DEFAULT NULL,
                    inv_numparte varchar(30) DEFAULT NULL,
                    inv_descripcion varchar(256) DEFAULT NULL,
                    inv_descove varchar(256) DEFAULT NULL,
                    inv_umc int(4) DEFAULT NULL,
                    inv_oma varchar(30) DEFAULT ' ',
                    inv_cantidad decimal(15,3) DEFAULT NULL,
                    inv_valorunitario decimal(16,4) DEFAULT NULL,
                    inv_valortotal decimal(16,2) DEFAULT NULL,
                    inv_moneda varchar(20) DEFAULT NULL,
                    inv_valorusd decimal(16,4) DEFAULT NULL,
                    inv_fraccUSA varchar(15) DEFAULT NULL,
                    inv_fraccGood varchar(15) DEFAULT NULL,
                    inv_preuniGood decimal(11,5) DEFAULT '0.00000',
                    inv_fraccPkg varchar(15) DEFAULT NULL,
                    inv_preuniPkg decimal(11,5) DEFAULT NULL,
                    inv_SKU char(2) DEFAULT NULL,
                    inv_PaisOrigen char(2) DEFAULT NULL,
                    inv_bultos int(11) DEFAULT NULL,
                    inv_tipoBulto int(11) DEFAULT NULL,
                    inv_agrupa int(11) DEFAULT '0',
                    PRIMARY KEY (pk_item)
                )",

                "CREATE TABLE IF NOT EXISTS cove_rfcconsulta (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    cove_factura varchar(25) DEFAULT NULL,
                    cove_rfcconsulta varchar(13) DEFAULT NULL,
                    cove_nombre varchar(120) DEFAULT NULL,
                    PRIMARY KEY (pk_item)
                )",

                "CREATE TABLE IF NOT EXISTS opauimg (
                    iImageID int(11) NOT NULL AUTO_INCREMENT,
                    imgNumeroOperacion varchar(30) CHARACTER SET latin1 DEFAULT NULL,
                    pk_referencia varchar(20) CHARACTER SET latin1 NOT NULL,
                    cove_factura varchar(100) CHARACTER SET latin1 DEFAULT NULL,
                    imgNameFile varchar(80) CHARACTER SET latin1 DEFAULT NULL,
                    strImageName varchar(256) CHARACTER SET latin1 NOT NULL,
                    imgImageData longblob,
                    imgtipo varchar(40) CHARACTER SET latin1 DEFAULT NULL,
                    imgtipodoc varchar(10) CHARACTER SET latin1 DEFAULT NULL,
                    imgRfc varchar(13) CHARACTER SET latin1 DEFAULT NULL,
                    imgEdocument varchar(30) CHARACTER SET latin1 DEFAULT NULL,
                    imgFechaEdoc date DEFAULT NULL,
                    imgNumeroTramite varchar(60) CHARACTER SET latin1 DEFAULT NULL,
                    imgCadenaTramite text CHARACTER SET latin1,
                    imgCadenaOriginal text CHARACTER SET latin1,
                    img_xml text CHARACTER SET latin1,
                    imgSello text CHARACTER SET latin1,
                    PRIMARY KEY (iImageID)
                )",

                "CREATE TABLE IF NOT EXISTS optr01 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) NOT NULL DEFAULT '0',
                    pk_patente char(4) NOT NULL DEFAULT '0000',
                    pk_pedimento char(7) NOT NULL DEFAULT '0000000',
                    pk_aduana char(3) NOT NULL DEFAULT '000',
                    pk_proyecto varchar(20) NOT NULL DEFAULT 'GENERAL',
                    ref_tipo char(1) DEFAULT '0',
                    ref_tipodoc char(1) NOT NULL DEFAULT '-',
                    ref_tipope char(3) DEFAULT '--',
                    ref_pedimento varchar(12) DEFAULT '--',
                    ref_clave char(2) DEFAULT '--',
                    ref_ctm varchar(20) DEFAULT '--',
                    ref_periodo varchar(7) DEFAULT '--',
                    ref_tipoctm int(11) DEFAULT '0',
                    ref_chr char(3) DEFAULT '--',
                    ref_regimen char(3) DEFAULT '--',
                    ref_destino char(2) DEFAULT '9',
                    ref_tipocambio decimal(8,5) DEFAULT '0.00000',
                    ref_pesokg decimal(14,5) DEFAULT '0.00000',
                    ref_aduanaes char(3) DEFAULT '--',
                    ref_transport1 char(2) DEFAULT '--',
                    ref_transport2 char(2) DEFAULT '--',
                    ref_transport3 char(2) DEFAULT '--',
                    ref_valorusd decimal(12,2) DEFAULT '0.00',
                    ref_valoradu decimal(13,0) DEFAULT '0',
                    ref_preciopag decimal(13,0) DEFAULT '0',
                    ref_valorseg decimal(12,3) DEFAULT '0.000',
                    ref_seguros decimal(12,3) DEFAULT '0.000',
                    ref_fletes decimal(12,3) DEFAULT '0.000',
                    ref_embalajes decimal(12,3) DEFAULT '0.000',
                    ref_otrosinc decimal(12,3) DEFAULT '0.000',
                    ref_marcas varchar(100) DEFAULT '--',
                    ref_fechapago date DEFAULT NULL,
                    ref_fechaentra date DEFAULT NULL,
                    ref_fechaext date DEFAULT NULL,
                    ref_fechapre date DEFAULT NULL,
                    ref_fechact date DEFAULT NULL,
                    ref_fechar1 date DEFAULT NULL,
                    ref_fechavence date DEFAULT NULL,
                    ref_efectivo decimal(13,0) DEFAULT '0',
                    ref_otros decimal(13,0) DEFAULT '0',
                    ref_total decimal(13,0) DEFAULT '0',
                    ref_status char(1) DEFAULT '-',
                    ref_referen varchar(20) DEFAULT '--',
                    ref_claveori char(2) DEFAULT '--',
                    ref_pedori varchar(12) DEFAULT '--',
                    ref_aduanaori char(3) DEFAULT '--',
                    ref_observa mediumtext,
                    ref_fi decimal(10,6) DEFAULT '0.000000',
                    ref_immex tinyint(3) DEFAULT '0',
                    ref_consolidado tinyint(3) DEFAULT '0',
                    ref_ecex tinyint(3) DEFAULT '0',
                    ref_ps tinyint(3) DEFAULT '0',
                    ref_virtual tinyint(3) DEFAULT '0',
                    ref_desperdicio tinyint(3) DEFAULT '0',
                    ref_sat int(11) DEFAULT '0',
                    ref_facturas int(11) DEFAULT '0',
                    ref_partidas int(11) DEFAULT '0',
                    ref_inventario int(11) DEFAULT '0',
                    origen int(11) DEFAULT '0',
                    PRIMARY KEY (pk_aduana,pk_patente,pk_pedimento),
                    UNIQUE KEY referencia (pk_referencia),
                    UNIQUE KEY pk_item (pk_item),
                    KEY pk_proyecto (pk_proyecto),
                    KEY ref_fechapago (ref_fechapago),
                    KEY ref_fechaext (ref_fechaext),
                    KEY ref_pedimento (ref_pedimento),
                    KEY ref_tipo (ref_tipo,ref_fechapago)
                )",

                "CREATE TABLE IF NOT EXISTS optr02 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) NOT NULL,
                    pk_factura varchar(30) DEFAULT NULL,
                    pk_cove varchar(30) DEFAULT NULL,
                    fac_clipro varchar(20) DEFAULT NULL,
                    fac_fecha date DEFAULT NULL,
                    fac_incoterm char(3) DEFAULT NULL,
                    fac_moneda char(3) DEFAULT NULL,
                    fac_valorme decimal(13,2) DEFAULT NULL,
                    fac_factorme decimal(10,8) DEFAULT NULL,
                    fac_valorusd decimal(13,2) DEFAULT NULL,
                    fac_vincula char(6) DEFAULT NULL,
                    fac_prorazon varchar(200) DEFAULT NULL,
                    fac_protaxid varchar(20) DEFAULT NULL,
                    fac_procalle varchar(150) DEFAULT NULL,
                    fac_procol varchar(100) DEFAULT NULL,
                    fac_procp varchar(10) DEFAULT NULL,
                    fac_prompo varchar(30) DEFAULT NULL,
                    fac_proedo varchar(30) DEFAULT NULL,
                    fac_pais varchar(65) DEFAULT NULL,
                    fac_cvepais char(3) DEFAULT NULL,
                    fac_efc char(2) DEFAULT NULL,
                    fac_OrdenCompra varchar(40) DEFAULT NULL,
                    fac_proyecto varchar(20) DEFAULT NULL,
                    fac_303 smallint(5) DEFAULT NULL,
                    fac_comercial varchar(30) DEFAULT '',
                    PRIMARY KEY (pk_item),
                    KEY pk_referencia_2 (pk_referencia),
                    KEY pk_referencia_3 (pk_referencia,pk_factura),
                    KEY pk_referencia (pk_referencia,pk_factura,fac_clipro)
                )",

                "CREATE TABLE IF NOT EXISTS optr03 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) NOT NULL,
                    pk_sec int(11) NOT NULL DEFAULT '1',
                    sec_fraccion varchar(10) DEFAULT NULL,
                    sec_fracciontlc varchar(20) DEFAULT NULL,
                    sec_desped varchar(200) DEFAULT NULL,
                    sec_subdiv char(1) DEFAULT NULL,
                    sec_vinculacio char(2) DEFAULT NULL,
                    sec_valoracion char(2) DEFAULT NULL,
                    sec_umc int(11) DEFAULT NULL,
                    sec_cantumc decimal(13,5) DEFAULT NULL,
                    sec_umt int(11) DEFAULT NULL,
                    sec_cantumt decimal(13,5) DEFAULT NULL,
                    sec_paiscv char(3) DEFAULT NULL,
                    sec_paisod char(3) DEFAULT NULL,
                    sec_valoradu decimal(12,2) DEFAULT NULL,
                    sec_valorpag decimal(12,2) DEFAULT NULL,
                    sec_preciouni decimal(13,5) DEFAULT NULL,
                    sec_valoragre decimal(12,2) DEFAULT NULL,
                    sec_valorusd decimal(12,2) DEFAULT NULL,
                    sec_efori char(2) DEFAULT NULL,
                    sec_efdes char(2) DEFAULT NULL,
                    sec_efcom char(2) DEFAULT NULL,
                    sec_efven char(2) DEFAULT NULL,
                    sec_arancel decimal(5,2) DEFAULT NULL,
                    sec_tipotasa int(11) DEFAULT NULL,
                    sec_formapago char(2) DEFAULT NULL,
                    sec_importe decimal(14,0) DEFAULT NULL,
                    sec_aranceltlc decimal(5,0) DEFAULT NULL,
                    sec_importetlc int(10) DEFAULT '0',
                    sec_exento int(10) DEFAULT '0',
                    sec_totalaranceltlc int(10) DEFAULT '0',
                    sec_status char(1) DEFAULT NULL,
                    sec_cambioreg decimal(13,7) DEFAULT NULL,
                    sec_secorig int(11) DEFAULT NULL,
                    sec_observa mediumtext,
                    PRIMARY KEY (pk_item),
                    UNIQUE KEY pk_referencia (pk_referencia,pk_sec)
                )",

                "CREATE TABLE IF NOT EXISTS optr04 (
                    pk_referencia varchar(20) NOT NULL,
                    inv_item int(11) NOT NULL AUTO_INCREMENT,
                    inv_itemorig int(11) DEFAULT '0',
                    inv_tipo char(1) NOT NULL,
                    inv_fechaes date NOT NULL DEFAULT '0000-00-00',
                    inv_factura varchar(30) NOT NULL,
                    inv_clipro varchar(12) DEFAULT ' ',
                    inv_numparte varchar(30) DEFAULT NULL,
                    inv_descom varchar(200) DEFAULT ' ',
                    inv_fraccion varchar(10) DEFAULT NULL,
                    inv_sec int(11) NOT NULL DEFAULT '1',
                    inv_anexouno tinyint(3) DEFAULT '0',
                    inv_vence date DEFAULT NULL,
                    inv_umc int(11) DEFAULT NULL,
                    inv_cantumc decimal(15,5) DEFAULT '0.00000',
                    inv_preuniumc decimal(12,5) DEFAULT '0.00000',
                    inv_umf int(11) DEFAULT NULL,
                    inv_cantumf decimal(15,5) DEFAULT '0.00000',
                    inv_preunifac decimal(12,5) DEFAULT '0.00000',
                    inv_importeme decimal(12,5) DEFAULT '0.00000',
                    inv_factorme decimal(12,5) DEFAULT '1.00000',
                    inv_importeusd decimal(12,5) DEFAULT '0.00000',
                    inv_valaduuni decimal(18,8) DEFAULT '0.00000000',
                    inv_peps decimal(15,5) DEFAULT '0.00000',
                    inv_dirigido decimal(15,5) DEFAULT '0.00000',
                    inv_desperdicio decimal(15,5) DEFAULT '0.00000',
                    inv_saldo decimal(15,5) DEFAULT '0.00000',
                    inv_referen varchar(20) DEFAULT ' ',
                    inv_status char(1) DEFAULT NULL,
                    inv_aexport tinyint(4) DEFAULT '0',
                    inv_anacional tinyint(4) DEFAULT '0',
                    inv_atlc tinyint(4) DEFAULT '0',
                    inv_pedimentos varchar(80) DEFAULT NULL,
                    inv_fechaped date DEFAULT NULL,
                    inv_aduanas varchar(40) DEFAULT NULL,
                    inv_activo char(1) DEFAULT 'S',
                    inv_explosionado tinyint(4) DEFAULT '0',
                    inv_pesokg decimal(16,5) DEFAULT NULL,
                    cove_item int(11) DEFAULT NULL,
                    inv_saldodesp decimal(15,5) DEFAULT '0.00000',
                    inv_saldoinicial decimal(15,5) DEFAULT '0.00000',
                    inv_despinicial decimal(15,5) DEFAULT '0.00000',
                    PRIMARY KEY (inv_item),
                    KEY pk_referencia (pk_referencia),
                    KEY pk_referencia_4 (pk_referencia,inv_factura),
                    KEY inv_numparte (inv_numparte,inv_tipo)
                )",

                "CREATE TABLE IF NOT EXISTS optr06 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) NOT NULL,
                    pk_con char(2) DEFAULT NULL,
                    con_concepto varchar(40) DEFAULT NULL,
                    con_fpago char(2) DEFAULT NULL,
                    con_importe decimal(14,0) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY pk_referencia (pk_referencia),
                    KEY pk_referencia_2 (pk_referencia,pk_con)
                )",

                "CREATE TABLE IF NOT EXISTS optr07 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) DEFAULT NULL,
                    con_sec int(11) DEFAULT NULL,
                    pk_con int(11) DEFAULT NULL,
                    con_concepto varchar(40) DEFAULT NULL,
                    con_tasa decimal(5,2) DEFAULT NULL,
                    con_tipotasa int(11) DEFAULT NULL,
                    con_fpago char(2) DEFAULT NULL,
                    con_importe decimal(14,0) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY pk_referencia (pk_referencia),
                    KEY pk_referencia_2 (pk_referencia,con_sec)
                )",

                "CREATE TABLE IF NOT EXISTS optr10 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    pk_referencia varchar(20) NOT NULL,
                    clave_des varchar(150) NOT NULL,
                    descripcion varchar(100) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY pk_referencia (pk_referencia)
                )",

                "CREATE TABLE IF NOT EXISTS optr11 (
                    pk_item int(11) NOT NULL AUTO_INCREMENT,
                    sec int(11) DEFAULT NULL,
                    pk_referencia varchar(20) NOT NULL,
                    clave_des varchar(150) NOT NULL,
                    descripcion varchar(100) DEFAULT NULL,
                    PRIMARY KEY (pk_item),
                    KEY pk_referencia (pk_referencia),
                    KEY pk_referencia_2 (pk_referencia,sec)
                )",


            ],

            "secenet" => [
                "CREATE TABLE products (
                    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    firstname VARCHAR(30) NOT NULL,
                    lastname VARCHAR(30) NOT NULL,
                    email VARCHAR(50),
                    reg_date TIMESTAMP)",
            ],
    ]

];
